
name: chianti_cloud
dependencies:
- python=3.6
- numpy
- scipy
- astropy
- h5py
- tornado=4.5.3
- requests
- pip:
  - fortranformat
  - plasmapy
  - git+git://github.com/wtbarnes/fiasco.git
  - h5json
  - h5pyd
  - watchdog
